function subtitle(array){
    document.querySelector("#subtitleP").innerHTML = array[0]
    let conterText = 1
    let currentTime = 0
    let Interval = setInterval(()=>{
        if((conterText*5) <= audio.duration){
            if((conterText*5) < audio.currentTime){
                document.querySelector("#subtitleP").innerHTML = array[conterText]
                conterText++
                currentTime =audio.currentTime
            }
            return
        } 
        clearInterval(Interval)
    }, 500)
}

let subPresentationDestiny = [
    "Bienvenido. En los próximos minutos recibirás un análisis",
    "sorprendente, como nunca antes has visto. Basado en la numerología cabalística,",
    "analizaré los números que rigen tu vida. ",
    "Recibirás un análisis personalizado a través de tu nombre y tu fecha de nacimiento.",
    "Has tomado una decisión en este momento, has elegido comprender mejor tu",
    "camino y las oportunidades que puedes tener en esta vida. La numerología",
    "es el puente entre quién eres ahora y el potencial que tienes para ser.",
    "Es un trampolín que te permite vivir tu mejor vida y ser lo mejor que puedes ser.",
    "Encontrarás respuestas a preguntas como ¿cuáles son tus habilidades y fortalezas? ",
    "¿Cuál es tu misión en esta vida? ¿Qué oportunidades",
    "te reserva el futuro? ¿Qué percepción transmites a los demás? ",
    "¿Cómo puedes atraer la abundancia?, entre muchas otras respuestas",
    "La numerología te ayudará a tomar decisiones, a mejorar tus relaciones",
    "y a atraer oportunidades. Por más difícil que parezca, descubrirás que has nacido",
    "con la capacidad de superar cualquier desafío. Encontrarás respuestas en",
    "tu número de destino, que es el más importante de tu análisis numerológico.",
    "Es la suma de todos los números de tu fecha de nacimiento y mostrará tu  ",
    "camino hacia la evolución. Su objetivo es orientarte, mostrarte las influencias de tu personalidad.",
    "Cuando las cosas no van bien en tu vida ",
    "y sientes que estás fracasando o quizás algo está obstaculizando tu éxito,",
    "es una señal de que no estás siguiendo tu destino.Cuando descubres tu destino,",
    "tu camino hacia la evolución, todo comienza a funcionar. Comienzas a prosperar,",
    "tus planes empiezan a dar resultado y tu vida mejora. ",
    "Ahora, déjame decirte lo que tu número de destino dice sobre ti."
]
let subPresentationMotivation = [
    "Pude realizar una lectura numerológica aún más personalizada y créeme,",
    "lo mejor está reservado para el final. Solo necesito llamar tu atención sobre",
    "una cosa antes de continuar. Las revelaciones que descubrí pueden",
    "sorprenderte un poco, ya que son íntimas y profundas. Te pido que",
    "escuches con la mente abierta, porque sé que lo que estás a punto de escuchar será de gran ayuda en tu vida.",
    "Comenzaremos con tu número de motivación.",
    "El número de motivación también se puede llamar número del alma. Representa tus deseos",
    "más profundos y todo lo que tu alma anhela para evolucionar en la vida y en las relaciones. ",
    "Se calcula sumando las vocales de tu nombre utilizando la tabla de numerología cabalística. ",
    "El número de motivación revela los deseos más profundos",
    "de tu alma, aquellos que ni siquiera tú mismo sabes que existen. ",
    "Este número te permitirá comprender de manera más profunda tus deseos y te llevará",
    "a alcanzar niveles más altos de realización. Saber cuáles son tus verdaderas ",
    "motivaciones te ayuda a trazar el camino hacia el éxito y la abundancia. ",
    "Hoy descubrirás lo que tus deseos y las motivaciones de tu alma dicen sobre ti."
]
let subPresentatiExpression = [
    "Hola nuevamente y me alegra que hayas decidido quedarte aquí para recibir tu análisis de expresión",
    "personalizado basado en tu nombre completo de nacimiento. Como verás",
    "en un momento, tu número de expresión es uno de los números más significativos ",
    "en tu análisis numerológico. Puede decir mucho sobre las habilidades únicas que tienes, ",
    "así como los desafíos que enfrentas. Te muestra qué dones ",
    "tienes desde tu nacimiento y predice hasta dónde puedes llegar al utilizarlos.",
    "Tu número de expresión se calcula utilizando el alfabeto cabalístico, sumando ",
    "los números que representan cada letra de tu nombre completo de nacimiento.",
    "Hacer estos cálculos puede ser un poco complicado, pero he calculado e interpretado ",
    "tu número de expresión para que no tengas que preocuparte por ello."
]
let subIntroductionMotication = [
    "Tu análisis numerológico dice mucho sobre ti y aún hay mucho más por explorar. ",
    "Me gustaría proporcionarte información sobre otras áreas de tu vida, ",
    "como tu verdadero propósito y tus relaciones. Al analizar tu número", 
    "de motivación, el cual representa tu interior y también puede ser llamado número del alma, ",
    "la influencia de tu número de motivación está en todas partes, en tu carrera,",
    "en tus amistades y en tu estilo de vida. Esto aclara la intención",  
    "detrás de tus decisiones y acciones. Puedes descubrir cuál",
    "es tu número de motivación y su significado en tan solo unos clics.",
    "Sin embargo, necesitaré más información sobre ti para asegurarme de que este análisis sea lo",
    "más preciso y personalizado posible. Te pido que completes tus datos arriba,",
    "por favor. También necesitaré tu dirección de correo electrónico,",
    "proporcionar esta información es importante para que pueda enviarte la transcripción",
    "de tu análisis para que la consultes cuando y donde quieras.",
    "Por favor, ingresa tu dirección de correo electrónico para que la recibas.",
    "Asegúrate de que los datos que nos proporcionaste sean correctos y luego haz clic en el botón",
    "'Continuar la lectura' para descubrir tu número de motivación", 
    "y desentrañar aún más sobre tu análisis numerológico."
]
let subIntroductionExpression = [
    "La numerología revela el plan de vida de cada ser humano y es una de las herramientas de", 
    "autoconocimiento más precisas y poderosas disponibles hasta el día de hoy.",
    "Ahora vamos a ver lo que el número de expresión representa en tu vida.", 
    "El número de expresión también esconocido como número de dones y talentos.", 
    "Demuestra cómo te expresas en el mundo, ¿cuáles son tus talentos?", 
    "Y muestra cómo te comportas con las demás personas. Aquí conocerás tu potencial", 
    "y cómo usarlo a tu favor, así como lo que deberías estar haciendo en esta vida", 
    "para alcanzar tus objetivos. Para conocer tu número de expresión,",
    "sumamos todas las letras de tu nombre basándonos en la tabla de numerología cabalística.", 
    "Tu nombre de nacimiento, al igual que tu fecha de nacimiento, influyen en",
    "quién eres. Al nacer y recibir un nombre de bautismo, el sonido", 
    "de las letras en tu nombre dice mucho sobre ti. Cada letra",
    "representa un número en la tabla cabalística de arriba, y la suma de estos números", 
    "forma un retrato fiel de quién eres hoy y de quién te convertirás en el futuro.",
    "Hoy descubrirás todo tu potencial y tendrás claridad sobre lo que eres capaz de lograr en tus", 
    "objetivos de vida. Para recibir un análisis gratuito de tu número de expresión",
    "basado en tu nombre completo de nacimiento, ingresa la información en el formulario", 
    "y haz clic en el botón para continuar con esta presentación."
]
let subEnd = {
    1: [
        "¡Uf, cuanta información para procesar, ¿verdad? Créelo o no,", 
        "todo lo que acabo de revelarte fue solo una muestra de todo lo que puedo descubrir, profundizando",
        "aún más con tu mapa numerológico, y debo admitir que te sorprendí con", 
        "lo que vi después de calcular y analizar tus números de destino, expresión y motivación.",
        "Tu combinación numerológica es extraordinaria. Como dije,",
        "todo esto es solo un resumen y lo que he mencionado hasta ahora solo ha demostrado de manera",
        "superficial quién eres y tus habilidades. Sin embargo,",
        "ahora tenemos más preguntas que respuestas, ¿verdad? Confieso que estoy", 
        "muy ansioso por dedicar unas horas más a tu análisis numerológico.",
        "Y lo que más quiero es resolver todas tus dudas y verte ganar la valentía para manifestar tu verdadera",
        "esencia y la abundancia que mereces en tu vida lo más pronto posible.",
        "Con estas respuestas, ¿podrías hacer realidad tus deseos más profundos?",
        "Tengo tantas cosas que decirte que es un poco complicado explicártelo por aquí.",
        "La información podría ser demasiado personal. Entonces,",
        "en caso de que estés interesado,"
    ],
    2: [
        "Me gustaría crear tu mapa numerológico completo. Descubrirás de manera simple y", 
        "clara cuál es tu verdadera misión y propósito de vida, y lo que debes hacer para",
        "aprovechar las oportunidades que te corresponden por derecho divino.",
        "También proporcionará explicaciones sobre la fase actual de tu vida y por qué estás atravesándola.",
        "Finalmente, entenderás todo lo que has experimentado en tus relaciones:",
        "atracciones inexplicables, deseos románticos y desilusiones amorosas.", 
        "Las decisiones que has tomado en tu carrera", 
        "y todos los obstáculos financieros tendrán sentido, y verás exactamente qué hacer para manifestar la",
        "abundancia y la riqueza que mereces. ¿Por qué deberías hacer tu mapa", 
        "numerológico? Revelaré un camino claro y la dirección para que alcances",
        "todos tus objetivos en la vida profesional, financiera, de relaciones",
        "y mucho más. Descubrirás de manera simple y clara cuál es tu verdadera misión",
        "y propósito de vida, así como la razón de tu existencia.",
        "Además, sabrás qué hacer para aprovechar las oportunidades que te corresponden por derecho divino.",
        "Conocerás las habilidades en las que debes trabajar para alcanzar",
        "el éxito más rápidamente, revelaré tus talentos ocultos y", 
        "dones para atraer oportunidades que antes eran inimaginables. Te mostraré tus",
        "fortalezas y debilidades para que puedas progresar en armonía con la vida que estás destinado(a)",
        "a vivir. Descubrirás las oportunidades y los momentos",
        "decisivos que el destino tiene reservados para ti, aumentando las posibilidades",
        "de alcanzar todos tus objetivos en la vida. Te revelaré los días más",
        "favorables para tomar decisiones importantes en tu vida profesional, financiera,",
        "personal, amorosa y en relación con tu salud.",
        "Te diré si tienes deudas kármicas y qué debes hacer para eliminar ese karma.",
        "En caso de que tengas lecciones y deudas kármicas, te presentaré un profundo",
        "entendimiento de tu vida de manera clara y objetiva. Descubrirás por qué atraes",
        "ciertas personas y situaciones a tu vida. Recibirás predicciones",
        "para los próximos doce meses de tu vida, indicando oportunidades y los mejores momentos",
        "para tomar acción y decisiones, lo que te permitirá aprovechar al máximo",
        "estos momentos al brindarte la oportunidad de prepararte de antemano.",
        "Y mucho más con el mapa numerológico en tus manos. Serás guiado(a)",
        "por el camino correcto para ingresar a tu propósito de vida y alcanzar tu máximo potencial."
    ],
    3: [
        "Cuando hagas clic en el botón de comprar ahora y completes tu compra, comenzaremos a trabajar",
        "de inmediato en la creación de tu mapa numerológico completo.", 
        "Además de una versión mucho más detallada de las lecturas que ya he realizado para ti, también",
        "recibirás interpretaciones minuciosas y detalladas de los otros elementos centrales", 
        "de tu análisis numerológico. Las diversas partes de tu personalidad",
        "definirán quién eres realmente. Y por primera vez, podrás",
        "comprender de una vez por todas cada una de ellas, todo dentro de tu mapa numerológico completo",
        "con más de setenta páginas sobre ti. Este informe te dirá todo",
        "lo que necesitas saber para volver a ser el maestro de tu propia vida, tomar",
        "las decisiones que definirán tu futuro. Al hacer clic en el botón de comprar ahora,",
        "serás redirigido a una página segura donde podrás finalizar tu compra de manera segura.",
        "Tu mapa numerológico completo revelará todos tus desafíos personales",
        "y todos los secretos y misterios que rodean tus números estarán disponibles en este informe.",
        "Estas interpretaciones iluminarán tu mente y te darán cuenta de cuál",
        "es la forma correcta de corregir tus fallos y avanzar hacia la abundancia.",
        "La pareja y la vida que siempre has deseado. Descubrirás de manera simple",
        "y clara cuál es tu verdadera misión y propósito de vida, y qué debes hacer",
        "para aprovechar las oportunidades que te corresponden por derecho divino. Este es tu momento,",
        "es hora de que descubras por qué aún no estás viviendo la vida que mereces.",
        "El valor de todo este informe y todos los beneficios que acabo de mencionar", 
        "es de trescientos cuarenta y siete reales. Sin embargo, hoy te daré",
        "un súper descuento. Para ti, que estás aquí en esta página, el valor",
        "de tu mapa numerológico completo será de solo ciento noventa y siete reales.",
        "Así es, te estoy dando ciento cincuenta reales de descuento, pero",
        "este descuento estará disponible solo una vez en esta página, así que no te lo pierdas.",
        "En otras palabras, si no aceptas este descuento y luego te arrepientes,",
        "este descuento ya no estará disponible. Y como estoy seguro",
        "de que este informe te brindará todas las respuestas que estásbuscando y te guiará a una transformación",
        "de vida este mismo año. Además del descuento especial, también recibirás",
        "una garantía de devolución de siete días. Esto significa que puedes",
        "enviar un correo electrónico a contacto arroba numerológico y se te reembolsará",
        "cada centavo que pagaste. Puedes estar seguro de esto, pero estoy seguro de que",
        "esto no sucederá. Tenemos estadísticas que demuestran queel mapa numerológico",
        "completo ha sido aprobado por más del noventa y nueve coma cincuenta y cinco por ciento de las personas",
        "que eligieron comprar. Ahora, solo te quedan dos opciones",
        "que te llevarán a destinos completamente diferentes. O bien,",
        "saldrás de esta página sin tu mapa numerológico completo, lo que te mantendrá estancado en",
        "el mismo lugar en el que estabas antes de encontrarnos.",
        "Hum, tomarás la decisión correcta y asegurarás un conocimiento completo sobre la magia de los números",
        "y todo lo que pueden decir sobre ti y lo que estádestinado a suceder en tu vida.",
        "Cómo superar tus debilidades, potenciar tus fortalezas y finalmente vivir la vida",
        "que siempre has deseado. Estás invitado a descubrir todo lo que tu mapa numerológicotiene",
        "para revelar. ¿Estás listo? Haz clic en",
        "el botón de comprar ahora para recibir tu mapa numerológico completo."
    ],
}
let subDestiny = {
    1: [
        "Tu número de destino es 1. Ese número me dice mucho acerca de ti.",
        "El número uno es como una estrella solitaria que brilla con una luz intensa e irresistible.",
        "Representa la singularidad, la individualidad y el liderazgo.",
        "Eres guiado por este número de destino y estás bendecido con una", 
        "fuerza interior e inigualable que te impulsa a sobresalir y alcanzar la grandeza.",
        "Imagina el número 1 como un líder intrépido, determinado a seguir su",
        "propio camino y dejar una marca duradera en el mundo. Tu viaje está guiado", 
        "por la pasión, la confianza y la voluntad de superar todos los obstáculos que se crucen en",
        "tu camino. Eres un alma valiente, lista para abrazar los desafíos y",
        "crear un futuro extraordinario. Tu personalidad está influenciada",
        "por el número 1 de destino. Se caracteriza por una autoconfianza inquebrantable y",
        "una voluntad inquebrantable de alcanzar el éxito. Posees una",
        "visión clara de tus objetivos y la determinación necesaria para perseguirlos incansablemente.",
        "Tu motivación se alimenta del deseo de ser el mejor en todo lo que haces",
        "y dejar tu marca única en el mundo. Además, tu personalidad",
        "cautivadora y carismática te convierte en un líder natural. Las personas",
        "se sienten naturalmente atraídas por tu energía magnética y buscan tu orientación y tu",
        "influencia positiva. Tu capacidad para inspirar a otros es un verdadero",
        "don que aportas al mundo. Sin embargo, recuerda que mientras sigues",
        "tu propio camino, es importante cultivar la humildad y la empatía.",
        "El número 1 de destino no se trata solo de lograr el éxito individual, sino también de",
        "usar tu liderazgo para beneficiar a los demás y crear un impacto positivo.",
        "Al equilibrar tu misión con la compasión, alcanzarás una grandeza",
        "verdaderamente significativa."
    ],
    2: [
        "Tu número de destino es el 2. Ese número me dice mucho acerca de ti.",
        "El número 2 de destino es como un hilo invisible que une a las personas y las",
        "experiencias en una danza divina de relaciones. Representa la necesidad",
        "de la asociación, la cooperación y el equilibrio. Eres guiado",
        "por este número de destino y estás bendecido con la habilidad de conectarte profundamente con los",
        "demás y traer armonía a todas las áreas de tu vida. Imagina el número 2",
        "como un Pacificador, un mediador que busca la unión y la colaboración.",
        "Tu viaje está guiado por el deseo de crear relaciones saludables y significativas,",
        "encontrando un equilibrio entre tus propias necesidades y las necesidades de los demás.",
        "Eres un alma gentil cuya fortaleza radica en la capacidad de unir",
        "a las personas y promover la armonía. Tu personalidad está influenciada",
        "por el número 2 de destino y se caracteriza por una sensibilidad emocional profunda",
        "y una habilidad excepcional para comprender los sentimientos de los demás.",
        "Posees empatía natural y una intuición aguda que te permiten crear conexiones auténticas",
        "y nutrir relaciones duraderas. Además, tu personalidad",
        "diplomática y conciliadora te convierte en un mediador hábil en situaciones de conflicto.",
        "Buscas soluciones armoniosas y siempre estás dispuesto a escuchar todos",
        "los puntos de vista antes de tomar decisiones. Tu influencia positiva y",
        "tu don para promover la colaboración son verdaderos regalos que aportas al mundo.",
        "Sin embargo, recuerda que, aunque es importante valorar y cuidar a los demás,",
        "también necesitas recordar tus propias necesidades y límites.",
        "Encuentra el equilibrio entre la búsqueda de la armonía y la afirmación de tu individualidad",
        "al establecer límites saludables y cultivar un sentido de autonomía.",
        "De esta manera, asegurarás que tus conexiones sean genuinas y gratificantes."
    ],
    3: [
        "Tu número de destino es 3. Ese número me dice mucho acerca de ti.",
        "El número tres de destino es como un rayo de sol radiante, iluminando",
        "el camino de la creatividad, la expresión y el optimismo.",
        "Representa la alegría de vivir, la habilidad de expresarte con libertad y la búsqueda",
        "incansable de la belleza y la armonía. Eres guiado por este número de destino y",
        "estás bendecido con el don de la creatividad y una energía contagiosa que inspira a todos",
        "a tu alrededor. Imagina el número tres como un artista visionario cuya expresión",
        "ilumina el mundo. Tu jornada está guiada por la búsqueda constante de la",
        "belleza y el significado en todas sus formas. Eres un alma llena de entusiasmo,",
        "lista para explorar nuevas perspectivas y compartir tu creatividad",
        "con el mundo. La personalidad influenciada por el número tres de destino se caracteriza",
        "por una imaginación fértil y una habilidad extraordinaria para expresarte.",
        "Posees un encanto magnético y una comunicación envolvente, cautivando",
        "a las personas con tus palabras y expresiones únicas. Tu motivación",
        "se alimenta del deseo de llevar color y alegría al mundo, inspirando a otros a seguir sus sueños.",
        "Además, tu personalidad encantadora y optimista te",
        "convierte en un verdadero catalizador de felicidad. Traes una energía",
        "contagiosa a cualquier situación, elevando el ánimo de las personas a tu alrededor.",
        "Tu influencia positiva y tu don de alentar a los demás son verdaderos regalos que aportas ",
        "al mundo. Sin embargo, recuerda que mientras buscas la alegría y",
        "la expresión creativa, también es importante encontrar equilibrio y enfocarte en la",
        "disciplina y la organización. Esto te permitirá desarrollar tu potencial",
        "al máximo y convertir tus ideas en realidad. Al armonizar tu",
        "lado creativo con un sentido de propósito, te convertirás en una fuerza",
        "poderosa e influyente."
    ],
    4: [
        "Tu número de destino es 4. Ese número me dice mucho sobre ti.",
        "El número cuatro de destino es como una base sólida que sostiene los pilares de la",
        "estabilidad, la organización y el trabajo duro. Representa la importancia",
        "de la planificación estratégica, la disciplina y el compromiso.",
        "Eres guiado por este número de destino y estás bendecido con la habilidad de construir",
        "un futuro sólido y duradero. Imagina el número cuatro como un",
        "arquitecto hábil, cuya visión crea estructuras sólidas y duraderas.",
        "Tu jornada está guiada por el deseo de establecer bases sólidas para lograr el éxito y ",
        "la seguridad. Eres un alma trabajadora, dispuesta a enfrentar desafíos",
        "y construir una vida plena y significativa. La personalidad influenciada",
        "por el número cuatro de destino se caracteriza por una ética de trabajo impecable",
        "y una mentalidad práctica. Posees una notable capacidad para planificar y",
        "organizar con eficiencia y excelencia en todo lo que haces. Tu motivación",
        "se alimenta del deseo de construir una base sólida para ti y para quienes",
        "te rodean. Además, tu personalidad confiable y responsable te convierte en un",
        "pilar de apoyo para los demás. Las personas confían en tu",
        "capacidad para tomar decisiones reflexivas y ofrecer orientación sabia.",
        "Tu influencia positiva y tu don para construir bases sólidas son verdaderos regalos",
        "que aportas al mundo. Sin embargo, recuerda que mientras buscas la estabilidad",
        "y el éxito, es importante encontrar equilibrio y flexibilidad.",
        "Aprende a adaptarte a los cambios y abrazar la creatividad en tu camino.",
        "Al combinar tu habilidad para la planificación estratégica con una mente abierta",
        "a nuevas posibilidades, te convertirás en un líder innovador e inspirador."
    ],
    5: [
        "Tu número de destino es 5. Ese número me dice mucho sobre ti.",
        "El número cinco de destino es como un viento impetuoso que sopla a tu favor,",
        "trayendo libertad, aventura y cambio. Representa la búsqueda",
        "de experiencias y la expansión de horizontes. Eres guiado por este número",
        "de destino y estás bendecido con un alma inquieta y una sed insaciable por descubrir todo",
        "lo que la vida tiene para ofrecer. Imagina el número cinco como un intrépido",
        "explorador cuya pasión por la aventura lo lleva a tierras desconocidas y posibilidades infinitas.",
        "Tu jornada está guiada por la búsqueda constante de libertad personal,",
        "crecimiento espiritual y la voluntad de abrazar cada oportunidad que el universo te ofrece.",
        "Eres un alma valiente, lista para enfrentar desafíos y",
        "abrazar la diversidad de la existencia. La personalidad influenciada por el",
        "número cinco de destino se caracteriza por un espíritu libre y una mente abierta.",
        "Posees una curiosidad insaciable y una energía contagiosa, cautivando",
        "a las personas a tu alrededor con tu carisma magnético. Tu motivación",
        "se alimenta de la búsqueda de nuevas experiencias y aprendizaje constante, así como",
        "de una conexión profunda con el mundo que te rodea. Además,",
        "tu personalidad versátil y adaptable te convierte en un verdadero agente de cambio.",
        "Encuentras belleza y significado en la diversidad, abrazando diferentes",
        "perspectivas y explorando caminos no convencionales. Tu influencia",
        "positiva y tu don para inspirar a otros a salir de su zona de confort son verdaderos regalos",
        "que aportas al mundo. Sin embargo, recuerda que mientras buscas",
        "la libertad y la expansión, es importante encontrar equilibrio y responsabilidad.",
        "Cultiva la disciplina y el enfoque. Canalizando tu energía",
        "para alcanzar tus objetivos más profundos. Al combinar tu sed",
        "de aventura con una mente estratégica, te convertirás en un verdadero pionero,",
        "llevando transformación e innovación allá donde vayas."
    ],
    6: [
        "Tu número de destino es 6. Ese número me dice mucho sobre ti.",
        "El número seis de destino es como un hábil jardinero, cultivando la",
        "floración de la armonía, el amor y la compasión en todas las áreas de tu vida.",
        "Representa la importancia de nutrir relaciones saludables, dedicarse al",
        "servicio a los demás y encontrar equilibrio entre el cuidado personal y el cuidado",
        "de quienes te rodean. Eres guiado por este número de destino y estás bendecido con la habilidad",
        "de crear conexiones profundas y irradiar un amor generoso. Imagina",
        "el número seis como un maestro del arte de vivir en armonía contigo mismo y con los demás,",
        "cuyo propósito es construir una comunidad unida y feliz.",
        "Tu jornada está guiada por la búsqueda de la paz interior, la empatía y el deseo de crear un impacto",
        "positivo en el mundo. Eres un alma compasiva, lista para",
        "extender la mano y ayudar a quienes lo necesitan. La personalidad",
        "influenciada por el número seis de destino se caracteriza por una naturaleza amorosa y acogedora.",
        "Te preocupas profundamente por el bienestar de los demás,",
        "siendo un pilar de apoyo y consuelo para quienes te rodean. Tu motivación",
        "se alimenta del deseo genuino de llevar armonía y felicidad a tu vida y a la vida",
        "de quienes amas. Además, tu personalidad atenta y dedicada te convierte",
        "en un verdadero catalizador de transformación. Posees una habilidad única",
        "para reunir personas, mediar conflictos y nutrir relaciones saludables.",
        "Tu influencia positiva y tu don para crear un ambiente de paz y",
        "equilibrio son verdaderos regalos que aportas al mundo. Sin embargo,",
        "recuerda que mientras buscas la armonía y el amor, también es importante cuidarte y",
        "establecer límites saludables. Atiende tu propia felicidad y bienestar,",
        "encontrando tiempo para el autocuidado y para reconectar con tu propia esencia.",
        "Al equilibrar el cuidado hacia los demás y el cuidado hacia ti mismo,",
        "te convertirás en un faro de luz que inspira a otros a encontrar su propio equilibrio interior."
    ],
    7: [
        "Tu número de destino es 7. Ese número me dice mucho sobre ti.",
        "El número siete de destino es como una fuente eterna de sabiduría, un faro",
        "de luz que ilumina tu búsqueda de conocimiento, comprensión y profundidad espiritual.",
        "Representa el viaje del alma en busca de la verdad interna,",
        "la conexión con lo divino y la expansión de la conciencia. Eres guiado",
        "por este número de destino y estás bendecido con la capacidad de sumergirte en las profundidades del",
        "conocimiento y desentrañar los misterios del universo. Imagina el",
        "número siete como un sabio solitario cuya búsqueda incesante del significado de la vida lo lleva",
        "a explorar los secretos ocultos del mundo. Tu jornada está guiada por la búsqueda de la",
        "perfección espiritual y la comprensión de la naturaleza humana.",
        "Eres un alma contemplativa, lista para desentrañar los enigmas de la existencia y",
        "compartir tu sabiduría con aquellos que estén listos para escuchar. La personalidad",
        "influenciada por el número siete de destino se caracteriza por una mente analítica y",
        "profunda. Posees una sed insaciable de conocimiento y una habilidad única",
        "para conectar puntos y ver más allá de las apariencias superficiales.",
        "Tu motivación se alimenta de la búsqueda de la verdad y la comprensión de las leyes universales",
        "que rigen la vida. Además, tu personalidad intuitiva y",
        "perspicaz te convierte en un verdadero buscador de respuestas. Eres capaz de",
        "sumergirte en las profundidades del pensamiento y la reflexión, revelando ideas profundas y",
        "reveladoras. Tu influencia positiva y tu don para brindar claridad y",
        "discernimiento son verdaderos regalos que aportas al mundo. Sin embargo,",
        "recuerda que mientras buscas sabiduría, también es importante equilibrar",
        "esa búsqueda con la práctica de la humildad y la conexión humana.",
        "Mantente abierto para aprender de los demás y compartir tu conocimiento de manera accesible y",
        "compasiva. Al equilibrar la búsqueda del conocimiento con la compasión hacia los demás,",
        "te convertirás en un faro de inspiración para los demás."
    ],
    8: [
        "Tu número de destino es 8. Ese número me dice mucho sobre ti.",
        "El número ocho de destino es como un arquitecto visionario, construyendo las",
        "bases sólidas de tu vida y moldeando tu destino con determinación y ambición.",
        "Representa el viaje de la manifestación material, la prosperidad y la conquista.",
        "Eres guiado por este número de destino y estás bendecido con una energía",
        "impulsiva y una habilidad innata para convertir sueños en realidad.",
        "Imagina el número ocho como un maestro de la abundancia y el éxito, cuyo viaje está",
        "regido por la búsqueda de la estabilidad financiera, el poder de influencia y la realización personal.",
        "Eres un alma emprendedora, lista para conquistar el",
        "mundo con tu visión y determinación. La personalidad influenciada",
        "por el número ocho de destino se caracteriza por una mentalidad de líder y realizador.",
        "Posees una perseverancia inquebrantable, una fuerza interior que te impulsa",
        "a superar obstáculos y lograr grandes hazañas. Tu motivación se alimenta",
        "del deseo de dejar una marca duradera en el mundo y alcanzar el éxito en todas las",
        "áreas de tu vida. Además, tu personalidad carismática y determinada te",
        "convierte en un verdadero capitán de tu propia vida. Eres capaz de tomar",
        "decisiones firmes, asumir responsabilidades y guiar a otros hacia el éxito.",
        "Tu influencia positiva y tu don para crear oportunidades son verdaderos regalos",
        "que aportas al mundo. Sin embargo, recuerda que mientras buscas",
        "el éxito material, también es importante cultivar valores como la integridad,",
        "la generosidad y la gratitud. Siempre busca equilibrar tu",
        "búsqueda de logros personales con la conciencia del impacto que tus acciones tienen en los demás.",
        "Al equilibrar la ambición con la compasión, te convertirás en un faro",
        "de inspiración para los demás."
    ],
    9: [
        "Tu número de destino es 9. Ese número me dice mucho sobre ti.",
        "El número nueve de destino es como un faro de luz, irradiando compasión,",
        "sabiduría y un espíritu altruista. Representa el viaje",
        "de la culminación del amor incondicional y la búsqueda de la elevación espiritual.",
        "Eres guiado por este número de destino y estás bendecido con un alma iluminada,",
        "destinada a dejar una marca indeleble en el mundo. Imagina el número nueve",
        "como un visionario cuyo viaje está impulsado por la profunda comprensión del poder del amor y",
        "la generosidad. Eres un alma altruista, lista para dedicar tu vida a causas",
        "nobles y al servicio a los demás. La personalidad influenciada por el",
        "número nueve de destino se caracteriza por una compasión profunda y un ardiente",
        "deseo de hacer del mundo un lugar mejor. Posees una sensibilidad única para",
        "percibir las necesidades de los demás y una notable capacidad para ofrecer apoyo y comprensión.",
        "Tu motivación se alimenta de la búsqueda de la armonía y la transformación",
        "positiva de la sociedad. Además, tu personalidad carismática y",
        "inspiradora te convierte en un verdadero líder humanitario.",
        "Eres capaz de catalizar cambios significativos, despertar la conciencia de las personas y",
        "motivarlas a actuar en pro del bien común. Tu influencia positiva y",
        "tu don para promover la curación son verdaderos regalos que aportas al mundo.",
        "Sin embargo, recuerda que mientras buscas el bienestar de los demás, también es",
        "importante cuidar de ti mismo. Mantén el equilibrio entre el servicio a los",
        "demás y el autocuidado para que puedas seguir siendo una fuente de inspiración a lo largo de tu jornada.",
        "Al nutrir tu propia alma, estarás capacitado para impactar",
        "positivamente la vida de quienes te rodean."
    ],
    11: [
        "El número 11 es un símbolo de inspiración divina y propósito elevado.",
        "Descubramos juntos las influencias transformadoras que ejerce sobre tu personalidad única.",
        "Estás influenciado por el número once de destino.",
        "Sepa que eres un alma excepcionalmente iluminada, un verdadero portador de la luz.",
        "Tienes un llamado divino para traer nuevas perspectivas, despertar",
        "la conciencia e inspirar a otros con tus ideas innovadoras.",
        "Tu intuición es intensa y confiable, lo que te permite acceder a una sabiduría profunda,",
        "y ver más allá de las apariencias superficiales. La personalidad moldeada",
        "por el número once se caracteriza por una sensibilidad y empatía notables.",
        "Eres un observador atento y captas las sutilezas del mundo que te rodea.",
        "Tu mente es una fuente inagotable de ideas creativas e ideas revolucionarias.",
        "Tienes la capacidad de ver más allá de los límites convencionales y ",
        "buscar soluciones innovadoras para los desafíos que se presentan. Además,",
        "estás dotado de una presencia magnética y carismática.",
        "Tu energía inspiradora atrae a las personas hacia ti y naturalmente son atraídas por",
        "tu sabiduría y tu capacidad para transmitir esperanza y optimismo.",
        "Tu voz tiene el poder de incitar cambios y motivar a otros a seguir sus sueños más audaces.",
        "Sin embargo, con esta poderosa energía también vienen grandes desafíos.",
        "El número once es un llamado para mantenerse equilibrado y anclado",
        "en tu verdad interior. Es importante cultivar la paciencia y la disciplina,",
        "ya que a veces el peso de tus visiones y responsabilidades puede ser abrumador.",
        "Recuerda cuidar de ti mismo y nutrir tu propia espiritualidad,",
        "encontrando tiempo para el descanso, la meditación y la conexión con la naturaleza.",
        "Eres un faro de luz en un mundo que a menudo se pierde en la oscuridad.",
        "Tu destino es traer inspiración, despertar conciencias y liderar con el ejemplo.",
        "Cree en ti mismo y en tu capacidad para manifestar tu",
        "visión única. Tienes el potencial de crear un impacto duradero y dejar un legado",
        "significativo."
    ],
    22: [
        "El número 22 es un símbolo de grandeza, habilidad y la capacidad de convertir",
        "los sueños en realidad. Vamos a explorar juntos las influencias increíbles que",
        "este número tiene en tu personalidad única. Si el número veintidós",
        "es tu número de destino, debes saber que eres un alma destinada a dejar un legado duradero en",
        "este mundo. Posees una habilidad excepcional para materializar ideas grandiosas",
        "y convertirlas en una realidad tangible. Tu mente está dotada",
        "de una visión amplia, lo que te permite ver más allá de lo común y anticipar posibilidades",
        "futuras. La personalidad moldeada por el número veintidós",
        "se caracteriza por tu habilidad para unir la practicidad y la intuición. Eres un",
        "maestro constructor capaz de planificar y ejecutar proyectos con una eficiencia impresionante.",
        "Tu determinación inquebrantable te impulsa a superar obstáculos y",
        "lograr resultados extraordinarios. Estás guiado por una voluntad inquebrantable",
        "de lograr grandes hazañas y dejar tu marca en el mundo. Además,",
        "posees una capacidad única para inspirar y motivar a las personas a tu alrededor.",
        "Tu presencia carismática irradia confianza y liderazgo, lo que te",
        "permite asumir roles destacados en cualquier empresa. Tu influencia se",
        "extiende más allá de los límites convencionales y eres capaz de movilizar equipos y",
        "comunidades enteras en favor de una causa mayor. Sin embargo, con esta",
        "inmensa capacidad de manifestación también vienen desafíos igualmente grandes.",
        "El número veintidós exige disciplina y equilibrio para asegurarte de que tus ambiciones no te abrumen.",
        "Es esencial que te mantengas conectado con tu intuición",
        "y fuente de inspiración interna. Recuerda que cada paso hacia tus objetivos",
        "debe ser cuidadosamente planeado y ejecutado con integridad.",
        "Eres un visionario con el poder de transformar el mundo que te rodea. Tu destino",
        "es construir un futuro mejor, llevando innovación y estabilidad a quienes te rodean.",
        "Cree en tu capacidad para crear cambios positivos y ten en cuenta",
        "que tienes el poder de hacer realidad tus sueños más audaces."
    ],
    33: [
        "El número 33 es la personificación de la maestría espiritual.",
        "Eres un alma iluminada que trae consigo un propósito divino para guiar e inspirar a aquellos que cruzan",
        "tu camino. Tu presencia es un faro de esperanza y curación,",
        "y tu capacidad para irradiar amor y compasión es simplemente incomparable.",
        "Tu personalidad se caracteriza por un corazón generoso y una dedicación incansable al servicio",
        "a los demás. Eres un ser genuinamente altruista que coloca",
        "las necesidades de los demás por encima de las tuyas. Tu sabiduría e intuición",
        "son profundas, lo que te permite comprender las complejidades de la existencia y ofrecer",
        "orientación y consuelo a quienes buscan tu ayuda. La influencia",
        "del número treinta y tres en tu personalidad trasciende los límites terrenales.",
        "Tu conexión con lo divino es fuerte e inquebrantable, lo que te permite acceder",
        "a una fuente infinita de sabiduría espiritual. Eres un canal poderoso para",
        "la energía divina, capaz de realizar curaciones profundas y llevar transformación",
        "positiva a quienes te rodean. Sin embargo, con este dominio espiritual viene",
        "una responsabilidad significativa. El número treinta y tres exige",
        "que estés en constante crecimiento y desarrollo personal. Es esencial que",
        "equilibres tu dedicación a los demás con la necesidad de autocuidado y autotransformación.",
        "Al nutrir tu propia alma, estarás más capacitado para",
        "cumplir con tu propósito divino y seguir siendo una fuente de inspiración para los demás."
    ],

}
let subExpression = {
    1:[
        "El número uno de expresión es como una llama brillante que ilumina el camino con su singularidad y",
        "autenticidad. Representa el viaje de la autoafirmación, el liderazgo",
        "y la fuerza interior. Eres guiado por este número de expresión y",
        "estás bendecido con una voz única y un magnetismo cautivador, destinado a dejar tu",
        "huella en la historia. Imagina el número uno como un pionero, aquel que",
        "abre nuevos caminos y aporta una visión original al mundo. Eres valiente y",
        "estás listo para liderar con confianza y determinación, inspirando a otros",
        "a seguir tu ejemplo. La personalidad influenciada por el número uno de expresión",
        "se caracteriza por una autoconfianza inquebrantable y una fuerza interior indomable.",
        "Posees una presencia magnética capaz de influir y cautivar a quienes te",
        "rodean. Tu motivación está impulsada por la búsqueda constante de lograr",
        "tus objetivos y manifestar tu visión única. Además,",
        "tu personalidad carismática y valiente te convierte en un verdadero líder.",
        "Eres capaz de inspirar, motivar y guiar a otros hacia el éxito. Tu influencia",
        "positiva y tu don para despertar el potencial de las personas son verdaderos regalos",
        "que traes al mundo. Sin embargo, recuerda que mientras buscas la afirmación",
        "personal, también es importante cultivar la empatía y la colaboración.",
        "Siempre busca escuchar las voces de los demás, valora la diversidad y trabaja",
        "en equipo para alcanzar objetivos comunes. Al combinar tu liderazgo",
        "inspirador con la capacidad de construir puentes, te convertirás en un agente",
        "de transformación verdaderamente poderoso."
    ],
    2:[
        "El número dos de expresión es como una danza armoniosa donde la cooperación yla diplomacia son los",
        "pasos principales. Representa el viaje de la asociación,",
        "el equilibrio y la sensibilidad emocional. Eres guiado por este número de",
        "expresión y bendecido con una habilidad única para conectarte profundamente con los demás",
        "y traer armonía a las relaciones. Imagina el número dos como un pacificador,",
        "alguien que busca el entendimiento mutuo y la colaboración.",
        "Eres un alma sensible, lista para escuchar y comprender las emociones de los demás,",
        "siendo un apoyo valioso en sus vidas. La personalidad influenciada",
        "por el número dos de expresión se caracteriza por una empatía natural y",
        "una habilidad excepcional para trabajar en equipo. Posees un don especial para mediar",
        "conflictos, encontrar soluciones armoniosas y crear un ambiente de paz a tu alrededor.",
        "Tu motivación está alimentada por la búsqueda de relaciones auténticas y",
        "conexiones significativas. Además, tu personalidad cariñosa",
        "y diplomática te convierte en un verdadero mediador. Eres capaz de",
        "suavizar tensiones, inspirar confianza y fomentar la colaboración entre las personas.",
        "Tu influencia positiva y tu don para construir puentes son",
        "verdaderos regalos que traes al mundo. Sin embargo, recuerda que mientras",
        "buscas armonía en las relaciones, también es importante cuidar de ti mismo.",
        "Reserva tiempo para nutrir tu propia paz interior y establecer límites saludables.",
        "Al equilibrar tus necesidades personales con el deseo de ayudar",
        "a los demás, te convertirás en una fuerza aún más poderosa en el mundo."
    ],
    3:[
        "El número tres de expresión es como una sinfonía celestial donde la creatividad y la expresión",
        "artística son las notas principales. Representa el viaje de la expresión",
        "creativa, la comunicación hábil y la alegría contagiosa.",
        "Eres guiado por este número de expresión y estás bendecido con un talento innato",
        "para expresarte a través de las artes, la escritura, la música o cualquier otra forma",
        "de expresión creativa. Imagina el número tres como un maestro de",
        "las palabras, alguien que tiene el don de encantar e inspirar los corazones.",
        "Eres un alma vibrante, lista para compartir tu voz única con el mundo,",
        "transmitiendo mensajes de esperanza, amor y belleza. La personalidad",
        "influenciada por el número tres de expresión está marcada por una energía ilimitada y",
        "radiante. Posees una habilidad extraordinaria para comunicarte de manera",
        "cautivadora e inspiradora, tocando profundamente las almas de quienes te escuchan.",
        "Tu motivación está alimentada por el deseo de expresar tu verdad interior y",
        "llevar luz y alegría al mundo. Además, tu personalidad carismática",
        "y encantadora te convierte en un verdadero narrador de historias.",
        "Eres capaz de involucrar a las personas en tu narrativa, despertando emociones",
        "y estimulando la imaginación. Tu influencia positiva y tu don",
        "para elevar el espíritu de las personas son verdaderos regalos que traes al mundo.",
        "Sin embargo, recuerda que mientras buscas expresar tu creatividad, también es",
        "importante encontrar equilibrio y practicar la autenticidad. Permítete ser",
        "vulnerable y mostrar tu verdadera esencia sin temor al juicio externo.",
        "Al abrazar tu singularidad y expresarte con autenticidad, te convertirás",
        "en una fuente de inspiración y empoderamiento para quienes te rodean."
    ],
    4:[
        "El número cuatro de expresión es como la sólida base de una magnífica construcción,",
        "donde la estabilidad, la disciplina y la practicidad son los cimientos.",
        "Representa el viaje de la materialización del trabajo duro y la eficiencia.",
        "Eres guiado por este número de expresión y estás bendecido con una habilidad excepcional",
        "para manifestar tus ideas de manera concreta y tangible. Imagina el",
        "número cuatro como el arquitecto maestro, aquel que tiene el don de convertir",
        "los sueños en realidad. Eres un alma práctica y determinada, lista para",
        "enfrentar desafíos y construir un futuro sólido a través de tu expresión cuidadosa.",
        "La personalidad influenciada por el número cuatro de expresión está marcada por",
        "una ética de trabajo impecable y una mentalidad enfocada. Posees una notable",
        "capacidad para planificar, organizar y ejecutar tareas con precisión y",
        "eficiencia. Tu motivación está alimentada por el deseo de crear una base",
        "sólida para tu éxito y el bienestar de quienes te rodean. Además,",
        "tu personalidad práctica y estructurada te convierte en un verdadero solucionador de problemas.",
        "Eres capaz de encontrar soluciones efectivas incluso en las situaciones",
        "más complejas e inspirar a otros con tu compromiso inquebrantable con la excelencia.",
        "Tu influencia positiva y tu don para crear una base estable son verdaderos regalos",
        "que traes al mundo. Sin embargo, recuerda que mientras buscas",
        "materializar tus metas, también es importante encontrar equilibrio y practicar la",
        "flexibilidad. Mantente abierto a nuevas ideas y adáptate a los cambios",
        "que surgen en tu camino. Al combinar tu habilidad de planificación con la capacidad",
        "de adaptación, te convertirás en una fuerza aún más poderosa en el mundo."
    ],
    5:[
        "El número cinco de expresión es como un viento vigorizante, donde la libertad,",
        "la aventura y la versatilidad son tus fuerzas impulsoras. Representa el",
        "viaje de la expansión, la búsqueda de experiencias y la curiosidad insaciable.",
        "Eres guiado por este número de expresión y estás bendecido con un espíritu",
        "aventurero y una habilidad excepcional para adaptarte a los cambios.",
        "Imagina el número cinco como un explorador intrépido, alguien que tiene el don de romper",
        "las barreras de la rutina y explorar nuevos horizontes. Eres un alma inquieta,",
        "lista para abrazar lo desconocido y sumergirte en nuevas experiencias con",
        "entusiasmo contagioso. La personalidad influenciada por el número cinco",
        "de expresión está marcada por una energía vibrante y una mentalidad abierta.",
        "Posees una capacidad extraordinaria para comunicarte de manera cautivadora y conectarte",
        "con las personas a un nivel profundo. Tu motivación está alimentada",
        "por el deseo de vivir la vida en su plenitud y compartir tus descubrimientos con el mundo.",
        "Además, tu personalidad versátil y adaptable te convierte en un",
        "verdadero agente de cambio. Eres capaz de adaptarte a diferentes circunstancias,",
        "encontrar oportunidades donde otros ven obstáculos e inspirar a otros con tu",
        "valentía y espíritu libre. Tu influencia positiva y tu don para explorar",
        "nuevos caminos son verdaderos regalos que traes al mundo. Sin embargo,",
        "recuerda que mientras buscas tu libertad y aventura, también es importante",
        "cultivar la estabilidad emocional y la disciplina. Equilibra tu deseo",
        "de explorar con la responsabilidad de mantener compromisos y cuidar tus relaciones.",
        "Al encontrar este equilibrio, te convertirás en una fuerza aún más magnética en el mundo."
    ],
    6:[
        "El número seis de expresión es como una armonía celestial, donde el amor,",
        "la compasión y el cuidado son las notas que resuenan en tu alma. Representa el",
        "viaje de la reconciliación familiar y la búsqueda del equilibrio en todas las áreas de la vida.",
        "Eres guiado por este número de expresión y estás bendecido con una sensibilidad",
        "excepcional para nutrir e inspirar a quienes te rodean. Imagina el",
        "número seis como un pacificador sereno, alguien que tiene el don de crear vínculos",
        "profundos y fortalecer las relaciones. Eres un alma compasiva y generosa,",
        "lista para ofrecer tu amor y apoyo incondicional a los demás.",
        "La personalidad influenciada por el número seis de expresión está marcada por una presencia",
        "cálida y un corazón abierto. Posees una capacidad notable para",
        "escuchar a los demás, brindar consuelo y servir como fuente de inspiración.",
        "Tu motivación está alimentada por el deseo de crear un entorno armonioso y amoroso",
        "donde las personas puedan florecer y encontrar su verdadero potencial.",
        "Además, tu personalidad acogedora y dedicada te convierte en un verdadero agente",
        "de sanación. Eres capaz de ver la belleza en las imperfecciones,",
        "ofrecer apoyo emocional e inspirar a otros con tu compasión. Tu influencia",
        "positiva y tu don para crear conexiones profundas son verdaderos regalos que traes al mundo.",
        "Sin embargo, recuerda que mientras buscas nutrir a los demás,",
        "también es importante cuidar de ti mismo. Reserva tiempo para",
        "recargar tus energías y establecer límites saludables. Al encontrar",
        "este equilibrio, te convertirás en una fuerza aún más radiante en el mundo."
    ],
    7:[
        "El número siete de expresión es como una fuente de sabiduría trascendental, donde la",
        "introspección, la intuición y la búsqueda de la verdad son tus fuerzas impulsoras.",
        "Representa el viaje hacia la comprensión profunda, la búsqueda",
        "del conocimiento y la conexión con lo divino. Eres guiado por este número de",
        "expresión y estás bendecido con una mente analítica y una capacidad única para sumergirte en las",
        "profundidades del pensamiento. Imagina el número siete como un ermitaño",
        "sabio, alguien que tiene el don de desentrañar los misterios del universo y ver más",
        "allá de las apariencias superficiales. Eres un alma contemplativa,",
        "lista para explorar los secretos del mundo y sacar a la luz las verdades ocultas.",
        "La personalidad influenciada por el número siete de expresión está marcada",
        "por una presencia tranquila y una mente aguda. Posees una capacidad",
        "excepcional de análisis, de buscar respuestas y comprender las complejidades del mundo",
        "que te rodea. Tu motivación está alimentada por el deseo de descubrir la",
        "verdad última y compartirla con los demás. Además, tu personalidad",
        "profunda y mística te convierte en un verdadero guía espiritual.",
        "Eres capaz de inspirar a otros a cuestionar la realidad, a explorar su propia",
        "espiritualidad y buscar la iluminación interior. Tu influencia poderosa y tu",
        "don de conectar lo terrenal con lo divino son verdaderos regalos que traes al mundo.",
        "Sin embargo, recuerda que mientras buscas la sabiduría, también es importante cultivar",
        "la conexión con el mundo que te rodea. Equilibra tu deseo",
        "de comprender lo desconocido con la apreciación por las experiencias terrenales y las relaciones",
        "significativas. Al encontrar este equilibrio, te convertirás",
        "en una fuerza aún más magnética en el mundo."
    ],
    8:[
        "El número ocho de expresión es como una fuerza cósmica donde el poder, la ambición y la",
        "manifestación se unen en una danza divina. Representa el viaje",
        "hacia la realización material y el equilibrio entre el mundo material y el espiritual.",
        "Eres guiado por este número de expresión y estás bendecido con una determinación",
        "inquebrantable para alcanzar el éxito y dejar una marca duradera en el mundo.",
        "Imagina el número ocho como un ejecutivo magistral, alguien que tiene el don de convertir",
        "los sueños en realidad y construir imperios con su visión audaz. Eres un",
        "alma ambiciosa y emprendedora, lista para enfrentar desafíos",
        "y lograr grandes hazañas. La personalidad influenciada por el número ocho",
        "está marcada por una presencia magnética y una mentalidad orientada al éxito.",
        "Posees una habilidad excepcional para liderar, tomar decisiones estratégicas y lograr",
        "resultados notables. Tu motivación está alimentada por el deseo de",
        "alcanzar reconocimiento, riqueza e influencia. Además,",
        "tu personalidad emprendedora y resiliente te convierte en un verdadero líder.",
        "Eres capaz de inspirar a otros con tu determinación inquebrantable y tu capacidad",
        "para superar desafíos. Tu influencia poderosa y tu don para materializar",
        "ideas son verdaderos regalos que traes al mundo. Sin embargo,",
        "recuerda que mientras buscas el éxito material, también es importante cultivar un sentido",
        "de propósito y gratitud. Equilibra tu búsqueda de poder con la compasión",
        "por los demás y una conexión con tu verdadero yo. Al encontrar este equilibrio,",
        "te convertirás en una fuerza aún más inspiradora en el mundo."
    ],
    9:[
        "El número nueve de expresión es como una llama ardiente donde la compasión, la",
        "generosidad y la búsqueda de la realización espiritual se unen en una sinfonía divina.",
        "Representa el viaje hacia la culminación de la sabiduría universal y la búsqueda",
        "del bienestar de toda la humanidad. Eres guiado por este número de expresión",
        "y estás bendecido con un alma altruista y una misión de servir a los demás.",
        "Imagina el número nueve como un humanitario inspirado, alguien que tiene el don de tocar",
        "corazones y transformar vidas con su amor incondicional. Eres una",
        "alma compasiva, lista para difundir luz y elevar el mundo que te rodea.",
        "La personalidad influenciada por el número nueve de expresión está marcada por una",
        "presencia cautivante y una conciencia elevada. Posees una habilidad excepcional",
        "para conectarte profundamente con las emociones de las personas, comprender",
        "sus necesidades y brindar una mano solidaria. Tu motivación",
        "está alimentada por el deseo de promover la curación, la transformación y la armonía en todos",
        "los aspectos de la vida. Además, tu personalidad caritativa",
        "e inspiradora te convierte en un verdadero líder espiritual. Eres capaz",
        "de despertar la compasión en los corazones de las personas, alentándolos a actuar",
        "en beneficio del bien común. Tu influencia poderosa y tu don para elevar la conciencia",
        "son verdaderos regalos que traes al mundo. Sin embargo,",
        "recuerda que mientras buscas la realización espiritual, también es importante cuidar de ti",
        "mismo y nutrir tu propio viaje de crecimiento. Equilibra tu",
        "dedicación hacia los demás con la autocompasión y la búsqueda de tu propia felicidad.",
        "Al encontrar este equilibrio, te convertirás en una fuerza aún más radiante en el mundo."
    ],
    11:[
        "El número once es un portal hacia dimensiones superiores, un símbolo de trascendencia",
        "y una intuición intensificada. Estás influenciado por este número",
        "especial, y debes saber que posees dones extraordinarios y una conexión profunda",
        "con el reino espiritual. Eres un mensajero divino, destinado a", 
        "traer ideas e inspiración a las personas a tu alrededor. La personalidad moldeada",
        "por el número once de expresión está dotada de una sensibilidad y percepción profundas.",
        "Tienes una intuición aguda y una capacidad innata para comprender la verdad",
        "oculta en las situaciones. Tu mente es un portal para ideas brillantes",
        "e innovadoras, capaces de transformar el mundo que te rodea.",
        "Además, tu carisma magnético y tu habilidad para cautivar a las personas te convierten",
        "en un líder natural. Tu presencia irradia magnetismo e inspira a otros",
        "a seguir tus pasos. Estás aquí para traer iluminación y despertar la",
        "conciencia colectiva. Sin embargo, con gran poder viene una gran responsabilidad.",
        "Es importante que utilices tus habilidades con sabiduría y",
        "discernimiento. Busca el equilibrio entre el mundo espiritual y el terrenal,",
        "entre la intuición y la acción concreta. Al encontrar esta armonía,",
        "serás capaz de manifestar tu visión elevada de manera tangible y concreta.",
        "También es crucial recordar nutrir tu propio viaje espiritual.",
        "Dedica tiempo al autodesarrollo, a la meditación y a la conexión con tu yo interior.",
        "Cultiva una mente abierta y muestra disposición para aprender y",
        "crecer de manera continua. Así, mejorarás aún más tus habilidades",
        "y ampliarás tu impactopositivo en el mundo."
    ],
    22:[
        "El número veintidós es un símbolo de manifestación extraordinaria y logros notables.",
        "Vamos a desentrañar las profundidades de este número y descubrir las influencias",
        "transformadoras que ejerce sobre tu personalidad única. Estás",
        "influenciado por el número veintidós de expresión. Debes saber que posees",
        "un don raro y una conexión profunda con la energía cósmica. Eres un maestro",
        "constructor, un arquitecto divino capaz de convertir sueños en realidad tangible.",
        "Tu visión es amplia, abarcando horizontes que la mayoría de",
        "las personas ni se atreverían a imaginar. La personalidad moldeada por el",
        "número veintidós se caracteriza por una determinación inquebrantable y un espíritu emprendedor.",
        "Posees una capacidad excepcional para visualizar y materializar grandes",
        "proyectos. Tu talento para planificar estratégicamente y organizar",
        "recursos te coloca en una posición única para crear algo verdaderamente impactante.",
        "Además, tu mente se nutre de creatividad e inspiración divina.",
        "Eres un solucionador de problemas nato, capaz de encontrar soluciones",
        "innovadoras incluso en las situaciones más desafiantes. Tu habilidad",
        "para unir elementos aparentemente dispares y transformarlos en algo coherente y práctico",
        "es un tesoro incalculable. Sin embargo, con grandes poderes",
        "vienen grandes responsabilidades. Estás llamado a liderar con integridad",
        "y compasión, manteniendo siempre una visión clara y una actitud equilibrada.",
        "Después de todo, el número veintidós es una invitación a utilizar tu",
        "poder de manera consciente y alineada con el bienestar general. Al hacerlo,",
        "te conviertes en un faro de esperanza e inspiración para los demás."
    ],
    33:[
        "El número treinta y tres es un símbolo de maestría espiritual y liderazgo altruista.",
        "Vamos a desentrañar las profundidades de este número y descubrir las influencias",
        "transformadoras que ejerce sobre tu personalidad única. Estás",
        "influenciado por el número treinta y tres de expresión, debes saber que eres un alma iluminada,",
        "un verdadero maestro de la compasión y la curación. Llevas contigo",
        "la capacidad de tocar profundamente el corazón de las personas a tu alrededor,",
        "trayendo amor, paz y armonía al mundo. Tu esencia está envuelta en sabiduría",
        "divina y tu presencia irradia un aura de paz y serenidad. La personalidad",
        "moldeada por el número treinta y tres se caracteriza por un sentido innato de responsabilidad",
        "hacia los demás. Eres un verdadero líder y mentor capaz de guiar",
        "e inspirar a aquellos que buscan tu apoyo. Tu empatía y comprensión son",
        "incomparables, lo que te permite entender las necesidades más profundas de las personas",
        "y ofrecer un apoyo genuino y alentador. Además, posees",
        "una intuición aguda y una conexión profunda con el reino espiritual. A través",
        "de la meditación y la práctica espiritual, eres capaz de acceder a conocimientos",
        "profundos y orientación divina. Tu alma es un puente entre el mundo terrenal y",
        "el trascendental, y estás llamado a compartir esta sabiduría con los demás.",
        "Sin embargo, con grandes dones espirituales vienen grandes desafíos.",
        "El número treinta y tres es un llamado para equilibrar tus propias necesidades",
        "con las de quienes te rodean. Es importante recordar cuidar de ti",
        "mismo y recargar tus energías para seguir siendo una fuente de luz e inspiración.",
        "Encuentra tiempo para la introspección y la nutrición espiritual, buscando",
        "siempre el equilibrio entre servir a los demás y cuidar de ti mismo."
    ],
}
let subMotivaion = {
    1:[
        "El número uno de motivación es una fuente poderosa de energía y determinación.",
        "Representa el fuego interior que arde dentro de ti, incitándote a buscar",
        "constantemente la excelencia y lograr grandes hazañas. Si estás",
        "influenciado por este número, estás bendecido con una motivación inquebrantable y una",
        "mentalidad orientada al éxito. Piensa en el número uno como un rayo de luz brillante",
        "que irradia coraje y confianza. Eres un verdadero pionero destinado",
        "a abrir tu propio camino y dejar una marca duradera en el mundo. Tu motivación",
        "innata impulsa a superar obstáculos, a perseverar cuando otros se rinden y a lograr",
        "resultados extraordinarios. La personalidad influenciada por el número",
        "uno de motivación está marcada por una determinación ardiente.",
        "Tienes una visión clara de lo que deseas lograr y estás dispuesto a hacer lo que sea necesario para convertir",
        "tus sueños en realidad. Nada puede detenerte cuando estás comprometido con",
        "un objetivo; tu fuerza interior te guía, inspirándote a superar límites y",
        "desafiar el status quo. Además, tu motivación contagiosa es",
        "capaz de influir e inspirar a los demás a tu alrededor. Eres una presencia",
        "magnética que atrae a las personas, ya que quedan cautivadas por tu pasión y tu voluntad",
        "inquebrantable de alcanzar el éxito. Tu determinación es un faro que ilumina",
        "el camino para aquellos que buscan orientación y motivación."
    ],
    2:[
        "El número dos de motivación es como un delicado hilo de armonía que impregna tu ser.",
        "Representa la fuerza de la cooperación, el equilibrio y la unión.",
        "Si estás influenciado por este número, estás bendecido con la habilidad de encontrar",
        "motivación a través de la convivencia con los demás y la búsqueda de relaciones significativas.",
        "Piensa en el número dos como una grácil danza entre dos almas,",
        "buscando la colaboración y la comprensión mutua. Tu motivación",
        "surge del deseo de relaciones saludables y de traer equilibrio y armonía a tu vida y al mundo que",
        "te rodea. La personalidad influenciada por el número dos de motivación",
        "está marcada por una sensibilidad compasiva y una habilidad excepcional para escuchar",
        "a los demás. Posees un don natural para percibir las necesidades y deseos",
        "de quienes te rodean, lo que te inspira a actuar en beneficio de todos.",
        "Tu motivación nace de la búsqueda del bienestar colectivo y encuentras fuerza en crear conexiones",
        "auténticas y significativas con los demás. Además,",
        "tu motivación colaborativa te convierte en un valioso compañero en cualquier empresa.",
        "Eres un hábil mediador, capaz de encontrar soluciones que satisfagan los intereses",
        "de todos los involucrados. Tu capacidad para trabajar en equipo y",
        "cultivar relaciones sólidas te coloca en una posición única para alcanzar metas",
        "conjuntas y promover un sentido de unidad y cohesión."
    ],
    3:[
        "Imagina el número tres como una paleta de colores vibrantes lista para ser explorada y",
        "combinada en obras de arte únicas. Tu motivación nace de la necesidad de",
        "crear, innovar y comunicarte de manera creativa. Eres un alma",
        "artística, una fuente inagotable de inspiración para aquellos a tu alrededor.",
        "La personalidad influenciada por el número tres de motivación se caracteriza por una",
        "creatividad innata y una habilidad excepcional para comunicarse. Posees un",
        "don natural para expresar tus pensamientos y sentimientos de manera clara y envolvente.",
        "Tu motivación es alimentada por la necesidad de compartir tus ideas y",
        "emociones con el mundo, inspirando e influenciando a otros a través de tu arte.",
        "Además, tu motivación creativa te convierte en un visionario.",
        "Eres capaz de ver más allá de lo obvio, capturando las sutilezas y matices",
        "del mundo que te rodea. Tu perspectiva única y tu fértil imaginación",
        "te impulsan a encontrar soluciones creativas para los desafíos que enfrentas.",
        "Y tienes la capacidad de inspirar a otros a ver más allá de las limitaciones de lo",
        "cotidiano. Sin embargo, recuerda que tu verdadera motivación se encuentra cuando",
        "permites que tu creatividad florezca en todas las áreas de tu vida. Abraza",
        "tu naturaleza expresiva y encuentra formas de integrar tu pasión por el arte en todo lo que",
        "haces, ya sea pintando, bailando, escribiendo u cualquier otra forma.",
        "Deja que tu creatividad sea la fuerza motriz que ilumina tu camino."
    ],
    4:[
        "El número cuatro de motivación es como un fundamento sólido y confiable que sustenta todas tus",
        "aspiraciones y deseos. Representa la estabilidad, la disciplina",
        "y la búsqueda de la excelencia. Si estás influenciado por este número,",
        "estás bendecido con una motivación intrínseca para construir una base sólida",
        "para tu éxito. Imagina el número cuatro como una estructura firme de una",
        "casa, construida con cuidado y precisión. Tu motivación nace",
        "de la necesidad de estabilidad y seguridad, buscando establecer un fundamento sólido",
        "para alcanzar tus objetivos. Eres un alma disciplinada,",
        "comprometida en dedicar tiempo y esfuerzo para construir un futuro sólido y duradero.",
        "La personalidad influenciada por el número cuatro de motivación se caracteriza por",
        "un enfoque metódico y determinado hacia la vida. Posees una ética",
        "de trabajo ejemplar y eres conocido por tu confiabilidad y responsabilidad.",
        "Tu motivación es alimentada por el deseo de construir una vida significativa y lograr el éxito",
        "a través del trabajo duro y la perseverancia incansable. Además,",
        "tu motivación disciplinada te convierte en un hábil planificador.",
        "Eres capaz de analizar y organizar los detalles de manera minuciosa, encontrando",
        "la mejor forma de alcanzar tus objetivos. Tu mente estructurada y",
        "enfocada impulsa a tomar decisiones sólidas y a crear rutinas que te ayudan a superar desafíos",
        "y alcanzar la excelencia en todas las áreas de la vida. Sin embargo,",
        "recuerda que tu verdadera motivación se encuentra cuando equilibras tu determinación con",
        "flexibilidad y adaptabilidad. Aunque la estabilidad es importante,",
        "recuerda abrir espacio para la creatividad y la espontaneidad en tu vida.",
        "Permítete explorar nuevas posibilidades y desafiarte más allá de tus zonas de confort,",
        "encontrando un equilibrio saludable entre la estructura y la flexibilidad."
    ],
    5:[
        "El número cinco de motivación es como un viento vigoroso que trae cambios y aventuras a tu vida.",
        "Representa la libertad, la versatilidad y la búsqueda de experiencias",
        "emocionantes. Si estás influenciado por este número, estás",
        "bendecido con una motivación intrínseca para explorar el mundo que te rodea y",
        "abrazar todas las oportunidades que la vida te ofrece. Imagina el número cinco como",
        "una invitación para aventurarte más allá de los límites conocidos, descubriendo",
        "nuevos horizontes y viviendo intensamente cada momento. Tu motivación nace",
        "de la necesidad de libertad y la búsqueda de experiencias emocionantes.",
        "Eres un alma inquieta, sedienta de variedad y ansiosa por expandir tus horizontes.",
        "La personalidad influenciada por el número cinco de motivación se caracteriza",
        "por una mente curiosa y un espíritu aventurero. Posees una energía",
        "contagiosa que inspira a los demás a liberarse de sus propias restricciones y abrazar la vida plenamente.",
        "Tu motivación se alimenta de la búsqueda incesante de nuevas experiencias,",
        "conocimientos y conexiones significativas. Además,",
        "tu motivación versátil te convierte en un maestro de la adaptación.",
        "Eres capaz de ajustarte a diferentes circunstancias y lidiar con cambios con facilidad",
        "y confianza. Tu mente ágil y abierta te permite reinventarte y",
        "adaptarte a cualquier desafío que surja en tu camino, transformando obstáculos en",
        "oportunidades de crecimiento y aprendizaje. Sin embargo, recuerda que tu",
        "verdadera motivación se encuentra cuando equilibras tu búsqueda de nuevas experiencias con la",
        "necesidad de estabilidad y responsabilidad. Encuentra el equilibrio entre la",
        "libertad y la responsabilidad, permitiéndote vivir plenamente mientras te ocupas de",
        "tus responsabilidades. De esta manera, podrás aprovechar al",
        "máximo la aventura de la vida sin dejar de lado tu sentido de compromiso."
    ],
    6:[
        "El número seis de motivación es como un rayo de luz brillante que ilumina el camino hacia la",
        "armonía y el amor. Representa la compasión, la responsabilidad y",
        "la búsqueda de equilibrio en las relaciones humanas. Si estás influenciado por",
        "este número, estás bendecido con una motivación intrínseca para cuidar de los demás",
        "y crear un ambiente de paz y armonía. Imagina el número seis como",
        "un cálido abrazo que envuelve a todos en su presencia, nutriendo corazones y mentes con",
        "amor incondicional. Tu motivación nace de la necesidad de crear conexiones",
        "significativas y de traer equilibrio a tu vida y a aquellos a tu alrededor.",
        "Eres un alma compasiva que encuentra satisfacción en cuidar de los demás, en ser una",
        "fuente de apoyo y amor. La personalidad influenciada por el número",
        "seis de motivación se caracteriza por una naturaleza amorosa y generosa.",
        "Posees una sensibilidad única para comprender las necesidades emocionales de los demás",
        "y eres capaz de ofrecer apoyo y orientación con compasión. Tu motivación",
        "se alimenta del deseo de nutrir y fortalecer las relaciones, construyendo",
        "una red de conexiones saludables y duraderas. Además,",
        "tu motivación responsable te convierte en un pilar de confianza y estabilidad.",
        "Asumes la responsabilidad de tus acciones y de las personas que amas, ofreciendo",
        "un sentido de seguridad y protección. Tu dedicación para cultivar un",
        "ambiente de armonía y paz te convierte en un mediador hábil, capaz de resolver conflictos",
        "y promover el entendimiento mutuo. Sin embargo, recuerda que tu verdadera",
        "motivación se encuentra cuando también cuidas de ti mismo. Equilibra tu generosidad",
        "con el autocuidado y la búsqueda de tu propio bienestar.",
        "Al fortalecer tu propio equilibrio emocional y físico, serás capaz de sostener tu motivación",
        "y ofrecer aún más amor y apoyo a los demás."
    ],
    7:[
        "El número siete de motivación es como un portal hacia la comprensión profunda y la conexión espiritual.",
        "Representa la búsqueda de la verdad, la introspección",
        "y el deseo de sumergirse en las cuestiones más complejas de la existencia.",
        "Si estás influenciado por este número, estás bendecido con una motivación intrínseca",
        "para explorar los misterios del mundo y encontrar respuestas más allá de lo obvio.",
        "Imagina el número siete como un sabio solitario en busca de conocimiento en las profundidades",
        "de una antigua biblioteca. Tu motivación nace de la necesidad de comprender",
        "el significado más profundo de la vida y encontrar respuestas a las preguntas más",
        "fundamentales. Eres un alma inquisitiva que encuentra satisfacción en la",
        "búsqueda de la sabiduría y en la exploración de las capas ocultas del universo.",
        "La personalidad influenciada por el número siete de motivación se caracteriza por una mente",
        "analítica y una sed insaciable de conocimiento. Posees una",
        "capacidad única para percibir las sutilezas del mundo que te rodea y establecer conexiones",
        "significativas entre ideas aparentemente dispares. Tu motivación se nutre",
        "de la búsqueda de la verdad y del deseo de comprender los misterios del universo.",
        "Además, tu motivación introspectiva te convierte en un buscador incansable",
        "de autoconocimiento. Te dedicas a la contemplación, la meditación",
        "y a la inmersión profunda en tu propio yo interior. Tu capacidad para",
        "reflexionar sobre tus experiencias y buscar la verdad dentro de ti te convierte en un guía inspirador",
        "para aquellos que buscan tu orientación. Sin embargo, recuerda que tu",
        "verdadera motivación se encuentra en el equilibrio entre la búsqueda del conocimiento y la conexión humana.",
        "Aunque es importante explorar el mundo intelectualmente, también",
        "es esencial nutrir relaciones significativas y abrirte a experiencias emocionales.",
        "Encuentra el equilibrio entre la soledad del pensamiento profundo y",
        "la conexión con otros seres humanos, enriqueciendo tu vida y la de quienes te rodean."
    ],
    8:[
        "El número ocho de motivación es como una llama ardiente que quema con la energía de la ambición,",
        "la determinación y la búsqueda del éxito. Representa la fuerza",
        "interna para lograr grandes realizaciones y materializar tus sueños más audaces.",
        "Si estás influenciado por este número, estás bendecido con una",
        "motivación intrínseca para prosperar y alcanzar la plenitud en todos los aspectos de la vida.",
        "Imagina el número ocho como un líder visionario capaz de convertir los",
        "sueños en realidad. Tu motivación nace de la necesidad de manifestar tu",
        "máximo potencial y alcanzar un estatus destacado. Eres un alma ambiciosa que",
        "encuentra satisfacción en lograr metas desafiantes y aprovechar las oportunidades que se",
        "presentan en tu camino. La personalidad influenciada por el número",
        "ocho de motivación se caracteriza por una determinación implacable y una mentalidad emprendedora.",
        "Posees una habilidad innata para asumir responsabilidades y liderar",
        "con confianza. Tu motivación se nutre de la búsqueda del éxito,",
        "la riqueza y la realización material, y estás dispuesto a trabajar incansablemente",
        "para alcanzar estos objetivos. Además, tu motivación práctica y",
        "organizada te convierte en un maestro de la planificación y la gestión de recursos.",
        "Tienes una habilidad excepcional para tomar decisiones sabias y estratégicas,",
        "y siempre estás atento a las oportunidades que pueden impulsar tu progreso.",
        "Tu mentalidad enfocada y determinada te coloca en el camino del éxito y te capacita",
        "para superar desafíos con resiliencia. Sin embargo,",
        "recuerda que tu verdadera motivación se encuentra en el equilibrio entre la búsqueda del éxito material",
        "y el cuidado de los aspectos emocionales y espirituales de la vida.",
        "Encuentra el equilibrio entre el crecimiento material y la conexión humana, cultivando",
        "relaciones significativas y nutriendo tu bienestar interior.",
        "De esta manera, alcanzarás un éxito verdaderamente significativo y duradero."
    ],
    9:[
        "El número nueve de motivación es como un faro brillante iluminando el camino de la comprensión,",
        "la compasión y la evolución espiritual. Representa la búsqueda",
        "de la verdadera esencia del ser, la búsqueda de la iluminación y el servicio altruista.",
        "Si estás influenciado por este número, estás bendecido con una",
        "motivación intrínseca para transformar el mundo a tu alrededor y alcanzar un estado de plenitud",
        "espiritual. Imagina el número nueve como un sabio maestro",
        "irradiando un aura de amor y compasión. Tu motivación nace de la necesidad de",
        "conectarte con la humanidad y ofrecer ayuda a los necesitados. Eres un alma",
        "generosa que encuentra satisfacción en servir a los demás y trabajar por el bienestar colectivo.",
        "La personalidad influenciada por el número nueve de motivación se caracteriza",
        "por una compasión profunda y una visión universal. Tienes la capacidad",
        "de ver más allá de las apariencias superficiales y entender la interconexión de todas",
        "las cosas. Tu motivación se nutre de la búsqueda del significado más elevado de la",
        "vida y el deseo de marcar la diferencia en el mundo. Además,",
        "tu motivación altruista te convierte en un agente de cambio. Te dedicas a",
        "causas nobles y estás dispuesto a sacrificar tu propia comodidad en beneficio del bien",
        "común. Tu capacidad para inspirar a los demás y liderar con el ejemplo es una fuerza",
        "poderosa que impulsa la transformación positiva en tu comunidad y más allá.",
        "Sin embargo, recuerda que tu verdadera motivación se encuentra cuando también",
        "cuidas de ti mismo. Equilibra tu altruismo con el autocuidado y el cultivo de",
        "tu propio viaje espiritual. Al nutrir tu propia evolución interior,",
        "te convertirás en una fuente aún más poderosa de luz e inspiración para los demás."
    ],
    11:[
        "El número once es un llamado divino para abrazar tu espiritualidad, explorar tu potencial",
        "máximo y convertirte en un verdadero visionario en el mundo.",
        "Tienes el número once como tu motivación. Estás destinado a ser un pionero,",
        "un líder audaz en tu campo de acción. Tu motivación está arraigada en una",
        "sed insaciable de conocimiento y un deseo incesante de trascender los límites",
        "convencionales. Posees una visión extraordinaria y una intuición aguda que te",
        "permite percibir posibilidades más allá de lo obvio y navegar por caminos inexplorados.",
        "La influencia del número once en tu personalidad es notable.",
        "Has adoptado una mente creativa y brillante, capaz de ver más allá de lo común",
        "y descubrir soluciones innovadoras para los desafíos que surgen en tu camino.",
        "Tu intuición es tu brújula, guiándote con sabiduría y perspicacia a lo largo",
        "de tu jornada. Además, tu presencia es magnética e inspiradora;",
        "las personas naturalmente se sienten atraídas por tu energía y tu capacidad",
        "para transmitir ideas complejas de manera clara y cautivadora.",
        "Posees el don de la comunicación, y tus palabras tienen el poder de despertar emociones profundas",
        "e impulsar a la acción. Tu carisma es innegable y tienes el potencial",
        "para influir e inspirar a las masas. Sin embargo,",
        "es importante recordar que con la motivación y el poder del número once también viene una gran responsabilidad.",
        "Tu jornada requiere valentía y determinación para enfrentar",
        "los desafíos que surgen en el camino. Puede que te encuentres con obstáculos y",
        "momentos de duda, pero es en esos momentos donde debes confiar en tu intuición y perseverar.",
        "Estás destinado a dejar un legado duradero e impactar la vida de las",
        "personas a tu alrededor."
    ],
    22:[
        "El número veintidós es un llamado divino para manifestar tus ambiciones más grandiosas y transformar",
        "el mundo que te rodea con tu visión visionaria. Tienes el número",
        "veintidós como tu motivación. Felicidades, pues eres un verdadero",
        "arquitecto del destino. Tu motivación está arraigada en una búsqueda implacable",
        "de la excelencia y una sed de logros incomparable. Posees una mente",
        "extraordinaria capaz de concebir planes ambiciosos y convertirlos en una realidad tangible.",
        "La influencia del número veintidós en tu personalidad es notable.",
        "Estás dotado de una combinación única de habilidades prácticas y visión",
        "inspiradora. Tu mente estratégica es capaz de derribar barreras y superar",
        "desafíos aparentemente insuperables. Tu pensamiento lógico y tu aguda",
        "intuición te permiten visualizar soluciones ingeniosas y llevar a cabo proyectos complejos con éxito.",
        "Además, tu presencia es magnética y empoderadora.",
        "Las personas naturalmente se sienten atraídas por tu determinación",
        "inquebrantable y tu capacidad para liderar con sabiduría. Eres un maestro",
        "en inspirar y motivar a los demás, capacitándolos para alcanzar sus propios objetivos",
        "y desafiar los límites de lo posible. Tu energía es contagiosa",
        "y irradias confianza y valentía a tu paso. Sin embargo, es",
        "importante recordar que con el poder del número veintidós de motivación viene una gran responsabilidad.",
        "Tu jornada requiere disciplina, enfoque y un compromiso",
        "inquebrantable. Puedes enfrentarte a obstáculos significativos y momentos de",
        "incertidumbre, pero es en esos momentos donde debes confiar en tu fuerza interior",
        "y perseverar. Estás destinado a dejar un legado duradero e inspirar la",
        "transformación positiva en el mundo."
    ],
    33:[
        "El número treinta y tres es un llamado divino para despertar el poder de tu alma y transformar el mundo",
        "con amor, compasión y servicio incondicional. Tienes el número",
        "treinta y tres como tu motivación. ¡Felicidades! Eres un",
        "alma iluminada, un mensajero de la paz y la armonía. Tu motivación",
        "está alimentada por una profunda conexión con lo divino y un ardiente",
        "deseo de marcar la diferencia en la vida de las personas a tu alrededor. ¡Wow!",
        "Eres un faro de esperanza que ilumina el camino hacia una humanidad más compasiva y amorosa.",
        "La influencia del número treinta y tres en tu personalidad es verdaderamente",
        "notable. Irradias un aura de bondad y empatía que atrae a las personas",
        "como un imán. Tu corazón compasivo puede sentir el dolor de los demás",
        "y ofrecer apoyo, comprensión y amor incondicional. Tu presencia",
        "calma las tormentas internas de las personas, brindando paz y serenidad.",
        "Además, posees dones de curación y orientación espiritual.",
        "Tu intuición está agudizada, lo que te permite percibir las necesidades",
        "más profundas de los demás y ofrecer palabras de sabiduría y consuelo.",
        "Tu sabiduría trascendente y tu capacidad de perdonar son una fuente de inspiración para aquellos",
        "que buscan equilibrio emocional y espiritual. Sin embargo,",
        "es importante recordar que el número treinta y tres de motivación conlleva una responsabilidad significativa.",
        "Tu jornada es un llamado a servir a los demás de manera altruista",
        "y desinteresada. Puedes enfrentar desafíos y sacrificios",
        "personales en el camino. Pero es en esos momentos cuando debes recordar la importancia",
        "de tu misión y la transformación positiva que puedes llevar al mundo."
    ]
}